### ISSUE TITLE
로그인 기능 구현

### ISSUE THREAD

**Issue by syg0629** [syg0629/wodLog#12]
## Description

> 로그인 기능을 구현합니다. 
> Kakao와 Google 소셜 로그인을 구현합니다.
> 일반 로그인은 테스트를 위한 것으로 `test@example.com`만 가능하게 합니다.
> 소셜 로그인 시 정보 별도 저장을 위한 Supabase userInfo 테이블 생성, 관련 트리거 및 함수를 생성합니다.
> 로그인한 사용자의 정보를 전역으로 사용하기 위해 Jotai를 도입합니다.

## Todo
- [x] 로그인 UI 구현
- [x] 소셜 로그인 기능 구현(Kakao, Google)
- [x] 일반 로그인은 `test@example.com`만 가능하게 구현
- [x] 사용자 입력에 따른 유효성 검사
- [x] Supabase userInfo 테이블, 관련 트리거 및 함수 생성
- [x] Jotai 도입
