### ISSUE TITLE
Record 페이지 리팩토링(쿼리 키 관리, Table 커플링 제거 등)

### ISSUE THREAD

**Issue by syg0629** [syg0629/wodLog#15]
## Description

> Record페이지는 이후 작성된 코드 스타일과 달라 전체적으로 코드 리팩토링을 합니다.

## Todo

- [x] 쿼리 키 관리 코드 분리
- [x] Record Table의 커플링 제거
- [x] 기록을 workoutType 순으로 정렬 방식 개선
- [x] 사용자 경험 개선을 위해 이미지 텍스트 추출 완료 후 안내 메세지 추가
- [x] UI 개선
