### ISSUE TITLE
기록 측정 방식에 따른 순위 갱신 코드 리팩토링

### ISSUE THREAD

**Issue by syg0629** [syg0629/wodLog#20]
## Description

> 크로스핏 기록 측정 방식에 따른 순위 갱신 코드를 리팩토링합니다.
> 기존 코드는 라운드와 개수만 가능했으며, 포맷팅 방법이 일반적이지 않아 수정합니다.
> 기록 측정 방식이 혼재되어 있는 경우 시간, 라운드, 개수 순으로 정렬합니다.
> 위 순서로 정렬된 내에서 시간은 짧은 순, 라운드는 많은 라운드 순, 개수는 많은 개수 순으로 정렬합니다.

## Todo

- [x] 시간, 라운드, 개수 순으로 정렬
- [x] 시간은 짧은 순, 라운드는 많은 라운드 순, 개수는 많은 개수 순으로 정렬
- [x] 기존 사용했던 포맷팅 방법 변경

## ETC

- 기존 코드는 `3R+12`의 경우, `3.12`로 Supabase에 저장하여 화면 렌더링 시 소수인지 정수인지 판단해 `replace()`로 `.`을 `R +`로 변경했었음
- 시간, 라운드, 개수 순으로 정렬 e.g. 200, 3R+12, 3R, 17:17   -> 17:17, 3R+12, 3R, 200 순으로 정렬

**Comment by bglgwyng** [comment]
최소시간단위를 1로해서 정수로 저장하는걸 권합니다. 3.12 -> 312. 어떤장점이 있을까요?

**Comment by syg0629** [comment]
자바스크립트는 부동소수점을 사용하기에 결과가 정확하지 않을 수 있어 정수를 사용하는 것이 좋습니다. 현재 부동소수점인 것을 정수로 바꾸면 데이터들이 모두 정수가 되니 일관성도 생기네요!

**Comment by syg0629** [comment]
> 최소시간단위를 1로해서 정수로 저장하는걸 권합니다. 3.12 -> 312. 어떤장점이 있을까요?

자바스크립트는 부동소수점을 사용하기에 결과가 정확하지 않을 수 있어 정수를 사용하는 것이 좋습니다. 현재 부동소수점인 것을 정수로 바꾸면 데이터들이 모두 정수가 되니 일관성도 생기네요!
