### ISSUE TITLE
회원 기록 및 순위를 볼 수 있는 Record 페이지 작성

### ISSUE THREAD

**Issue by syg0629** [syg0629/wodLog#4]
## Description

> 전 회원 기록 및 순위를 볼 수 있는 Record 페이지를 작성합니다.
> Record 신규 등록 / 상세 페이지를 작성합니다.
> 등급별 Record를 보여주기 위한 Table 컴포넌트를 작성합니다.
> 신규 Record가 입력되면 상세 페이지의 순위가 자동으로 갱신됩니다.
> 신규 Record는 이미지를 업로드 하면 이미지 속 글자를 인식하여 추출하는 OCR 라이브러리(Tesseract)를 사용합니다.

## Todo

- [x] Record 상세 페이지 UI
- [x] Table 컴포넌트 작성
- [x] Record 신규 등록 페이지 UI 
- [x] 신규 Record를 입력 시 상세 페이지 순위 갱신
- [x] 신규 Record 이미지 업로드, 이미지 미리보기
- [x] Tesseract 라이브러리 설정

## ETC

- Tesseract OCR 인식 정확도 파악 필요
