### ISSUE TITLE
supabase 설정

### ISSUE THREAD

**Issue by syg0629** [syg0629/wodLog#6]
## Description

> Supabase를 설정합니다.

## Todo

- [x] Supabase 홈페이지에서 프로젝트 생성
- [x] Supabase 홈페이지에서 데이터베이스 설정
- [x] Supabase RLS(Row Level Security) 설정
- [x] 환경변수 설정
- [x] 타입 생성
- [x] 연결 테스트
