### ISSUE TITLE
오늘의 운동 공지를 위한 WOD 페이지 작성

### ISSUE THREAD

**Issue by syg0629** [syg0629/wodLog#9]
## Description

> 오늘의 운동인 WOD(Workout Of the Day)를 알려주는 페이지를 작성합니다.
> WOD 신규 등록/수정, 목록, 상세 페이지를 작성합니다.
> 전체적으로 Notice 페이지와 비슷하나 목록 화면은 UI를 다르게 작성합니다(Notice: 내용 미리보기 O / WOD: 내용 미리보기 X)
> 홈 페이지 진입 시 오늘의 WOD를 보여주나 아직 등록되지 않았으면 "등록되지 않음"을 사용자에게 알려줍니다.

## Todo

- [x] Notice 페이지를 리팩토링하여 공통 컴포넌트 생성
- [x] WOD 목록 페이지 UI -> Notice와 달리 preview 없음
- [x] Supabase WOD 테이블 생성
- [x] Home 진입 시 금일 WOD 노출 혹은 아직 등록되지 않음을 공지
